### PR TITLE
DAOS-17868 common: Reclaim empty slabs under memory pressure to impro…

### PR DESCRIPTION
**Pull request by sherintg**
…ve evictable bucket utilization

Fixes an issue with phase-2 allocator where allocation slabs with zero allocated blocks were not being reclaimed under memory pressure. This led to underutilization of evictable buckets.

### Steps for the author:

* [ ] Commit message follows the [guidelines](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Appropriate [Features or Test-tag](https://daosio.atlassian.net/wiki/spaces/DC/pages/10984259629/Test+Tags) pragmas were used.
* [ ] Appropriate [Functional Test Stages](https://daosio.atlassian.net/wiki/spaces/DC/pages/12147556353/CI+Functional+Test+Stages) were run.
* [ ] At least two positive code reviews including at least one code owner from each category referenced in the PR.
* [ ] Testing is complete. If necessary, forced-landing label added and a reason added in a comment.

#### After all prior steps are complete:
* [ ] Gatekeeper requested (daos-gatekeeper added as a reviewer).

### CODE REVIEW

**Comment by daosbuild3** [comment]
Test stage Unit Test bdev with memcheck on EL 8.8 completed with status FAILURE.  https://jenkins-3.daos.hpc.amslabs.hpecorp.net/job/daos-stack/job/daos/job/PR-16699/1/display/redirect

**Comment by sherintg** [comment]
@wangshilong @NiuYawei Can you please review and approve this PR.

**Review by wangshilong — APPROVED** [review]

**Comment by daltonbohning** [comment]
@sherintg I created a revert PR for this: #16776
Because after merging, build is now failing
https://github.com/daos-stack/daos/actions/runs/17271146986/job/49015964848
```
#41 260.4 src/vos/tests/vts_wal.c:666:11: error: call to undeclared function 'vts_ctx_init_ex'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
#41 260.4   666 |         rc     = vts_ctx_init_ex(&test_args.ctx, MDTEST_VOS_SIZE_V2, MDTEST_META_BLOB_SIZE_V2);
#41 260.4       |                  ^
#41 260.4 src/vos/tests/vts_wal.c:666:11: note: did you mean 'vts_ctx_init'?
#41 260.4 src/vos/tests/vts_common.h:97:1: note: 'vts_ctx_init' declared here
#41 260.4    97 | vts_ctx_init(struct vos_teInstall file: "utils/config/daos_control.yml" as "/opt/daos/etc/daos_control.yml"
#41 260.4 st_ctx *tcx, uint64_t scm_sz, uint64_t meta_sz, uint64_t datas_sz,
#41 260.4       | ^
```
